# Generated by Django 5.1.3 on 2024-11-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_room_capacity_alter_payment_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
    ]
